name: "Setup PHP and Composer"
description: "Sets up PHP with all required extensions and installs Composer dependencies with caching"

inputs:
  php-version:
    description: "PHP version to setup"
    required: false
    default: "8.4"
  coverage:
    description: "Enable xdebug for coverage collection"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, sqlite3, json${{ inputs.coverage == 'true' && ', xdebug' || '' }}
        coverage: ${{ inputs.coverage == 'true' && 'xdebug' || 'none' }}

    - name: Get Composer Cache Directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: |
          vendor
          ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ inputs.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ inputs.php-version }}-composer-

    - name: Install Composer dependencies
      shell: bash
      run: composer install --prefer-dist --no-interaction --no-progress
