name: Pest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php-composer
        with:
          coverage: "true"

      - name: Execute tests with coverage
        run: vendor/bin/pest --parallel --coverage --coverage-text --min=80
